### ISSUE TITLE
Please install sqlite3 package manually

### ISSUE THREAD

**Issue by Channndiii** [lijinma/wechat_spider#13]
ubuntu16
安装wechat_spider后
**尝试安装**
sudo npm install sqlite3 -g
**输出**
> sqlite3@3.1.8 install /usr/local/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@7.8.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/usr/local/lib/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Database::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/database.cc:133:96: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
 orceSet(Nan::New("filename").ToLocalChecked(), info[0].As<String>(), ReadOnly);
                                                                              ^
In file included from /home/chandi/.node-gyp/7.8.0/include/node/v8.h:26:0,
                 from /home/chandi/.node-gyp/7.8.0/include/node/node.h:42,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/chandi/.node-gyp/7.8.0/include/node/v8.h:2956:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/home/chandi/.node-gyp/7.8.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/database.cc:134:86: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
 .This()->ForceSet(Nan::New("mode").ToLocalChecked(), Nan::New(mode), ReadOnly);
                                                                              ^
In file included from /home/chandi/.node-gyp/7.8.0/include/node/v8.h:26:0,
                 from /home/chandi/.node-gyp/7.8.0/include/node/node.h:42,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/chandi/.node-gyp/7.8.0/include/node/v8.h:2956:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/home/chandi/.node-gyp/7.8.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
../src/database.cc:144:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
../src/database.cc:230:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
../src/database.cc:525:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
../src/database.cc:625:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Statement::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/statement.cc:103:74: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("sql").ToLocalChecked(), sql, ReadOnly);
                                                                          ^
In file included from /home/chandi/.node-gyp/7.8.0/include/node/v8.h:26:0,
                 from /home/chandi/.node-gyp/7.8.0/include/node/node.h:42,
                 from ../src/statement.cc:2:
/home/chandi/.node-gyp/7.8.0/include/node/v8.h:2956:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/home/chandi/.node-gyp/7.8.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:
../src/statement.cc:118:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:322:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:370:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:438:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:504:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:601:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:724:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY /usr/local/lib/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp

**Comment by lijinma** [comment]
wechat_spider 安装成功了吗？

**Comment by Channndiii** [comment]
wechat_spider --help 就会显示 Please install sqlite3 package manually

**Comment by Channndiii** [comment]
重新安装wechat_spider解决了XD
可是从公众号进入历史消息里面 显示的是 “网络出错，轻触屏幕重新加载：-1202” 之前有过这种情况吗?

**Comment by lijinma** [comment]
@Channndiii 是 iOS 吧？iOS 请查看

https://github.com/lijinma/wechat_spider/issues/3

**Comment by Channndiii** [comment]
@lijinma 十分感谢:D 爬虫已经可以运行 但运行过程中发现一些问题：
1. 查看公众号历史消息后 可以自动刷新 但一直显示“3秒后没有自动刷新请手动刷新” 期间页面会不断刷新 一段时间后 页面停止刷新但**不显示**“一个公众号采集完成” 导出到csv后 **记录只有10条左右** 试了几个公众号都如此
2. 重新运行爬虫 进入公众号历史消息 打开最新文章 可以自动刷新 并且最后会**显示**“一个公众号采集完成” 导出到csv后 **记录也是只有10条左右** 试了几个公众号都如此
3. 运行过程中 terminal会显示：
Unhandled rejection SequelizeBaseError: Validation error
    at Query.formatError (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/usr/local/lib/node_modules/wechat_spider/node_modules/sqlite3/lib/trace.js:19:31)
请问这样算正常爬取吗？

**Comment by lijinma** [comment]
我试了一下，果然有问题，微信有一些调整。。。。我想想办法处理。

**Comment by lotusct** [comment]
执行  wechat_spider --help 时，就会报错：
throw new Error('Please install sqlite3 package manually');
      ^
Error: Please install sqlite3 package manually
请问具体如何解决？

**Comment by Channndiii** [comment]
@lotusct 我当时remove原来的wechat_spider 然后重新按步骤安装就好了

**Comment by Cybs** [comment]
#16

**Comment by bbsmsm** [comment]
throw new Error('Please install sqlite3 package manually');
^
Error: Please install sqlite3 package manually

mac上报这个错怎么解决？

**Comment by Cybs** [comment]
同求翻页数据的解决

**Comment by hejiheji001** [comment]
@coreyfu  npm install -g sqlite3

**Comment by bbsmsm** [comment]
已解决，sqlite版本与node不匹配

**Comment by R1hug0** [comment]
你装的是什么版本的nodejs,我也一直接安装不成功,

**Comment by R1hug0** [comment]
要进入wechat_spider工程目录下安装相应在依赖....

**Comment by garfieldkai** [comment]
重新安装了，还是不行。win10 64位，npm 5.3.0，python 2.7.13，wechat_spider 1.0.9，sqlite3 3.1.8执行 wechat_spider --help 时，就会报错：
throw new Error('Please install sqlite3 package manually');
^
Error: Please install sqlite3 package manually
请问具体如何解决？

**Comment by ScnuWang** [comment]
PS C:\Users\scnuj\Desktop> wechat_spider --help
C:\Users\scnuj\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
      ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (C:\Users\scnuj\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:25:13)
    at new SqliteDialect (C:\Users\scnuj\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\sequelize\lib\dialects\sqlite\index.js:12:28)
    at new Sequelize (C:\Users\scnuj\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\sequelize\lib\sequelize.js:233:18)
    at Object.<anonymous> (C:\Users\scnuj\AppData\Roaming\npm\node_modules\wechat_spider\lib\db.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\scnuj\AppData\Roaming\npm\node_modules\wechat_spider\lib\csv.js:1:72)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
重新安装了很多次了，还是不行，sqlite3已经安装好了呢
PS C:\Users\scnuj\Desktop> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>>

**Comment by ChinaMingQi** [comment]
npm 版本太新了？我遇到过这种情况，我把是我npm版本从5.6降到4.2。再从新安装wechat_spider就行了。
