### ISSUE TITLE
抓取运行时报错

### ISSUE THREAD

**Issue by Cybs** [lijinma/wechat_spider#16]
错误信息：
`Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/Cybs/.nvm/versions/node/v4.4.5/lib/node_modules/wechat_spider/node_modules/.3.30.4@sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/Users/Cybs/.nvm/versions/node/v4.4.5/lib/node_modules/wechat_spider/node_modules/.3.30.4@sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/Users/Cybs/.nvm/versions/node/v4.4.5/lib/node_modules/wechat_spider/node_modules/.3.1.8@sqlite3/lib/trace.js:19:31)`

运行环境mac，虽然报错了，但是在执行目录下生成了wechat.sqlite文件。

**Comment by lijinma** [comment]
感觉我用 sqlite3 就是个错误，因为需要编译。

**Comment by Cybs** [comment]
@lijinma 根本原因是数据问题导致写入错误？

**Comment by lijinma** [comment]
不太确定，我建议你自己看代码，自己来修改不要使用 sqlite，用 mysql 什么的，可以吗？

**Comment by Cybs** [comment]
@lijinma 我先试试

**Comment by Cybs** [comment]
已解决，原因是db会对已存在的记录继续进行insert，修改了一下db.js的insertOne函数：
`var insertOne = function (author, biz, appmsgid, title, contentUrl, cover, digest, idx, sourceUrl, createTime) {
  sequelize.sync().then(function(){
    console.log('Post.create', idx);
    return Post.create({
      author: author,
      biz: biz,
      appmsgid: appmsgid,
      title: title,
      contentUrl: contentUrl.replace(/\\\//g, "/"),
      cover: cover.replace(/\\\//g, "/"),
      digest: digest.replace("&nbsp;", " "),
      idx: idx,
      sourceUrl: sourceUrl.replace(/\\\//g, "/"),
      createTime, createTime,
    })
  }).catch(function () {
    console.log('Post.findOne', idx);
    return Post.findOne({
      where:{
        contentUrl: contentUrl.replace(/\\\//g, "/"),
      }
    })
  })
};`

就是判断一下，如果insert失败则update。

另外我发现readme里面最好一步有点误导了，我开着历史记录列表，发现一直在记录页面中刷新，以为有bug，后来“不小心”点进文章页面，发现就会一篇篇自动抓取了。

**Comment by bbsmsm** [comment]
@Cybs 有遇到这个错吗，怎么解决？
mac上wechat_spider安装成功，运行wechat_spider --help时报错：
/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
      ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/sequelize.js:233:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/wechat_spider/lib/db.js:2:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/wechat_spider/lib/csv.js:1:72)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by Cybs** [comment]
@coreyfu 我没遇到这个哦，我看你也有在前面的issue里问了，那里的方法不行？ 重装试试？

**Comment by vnqiubiao** [comment]
@coreyfu 我遇到的这个问题的解决方法是，用cnpm去国内镜像下包，国外有些包太难下了。
