### ISSUE TITLE
历史文章列表页面反复刷新，查看shell出现如下错误

### ISSUE THREAD

**Issue by rayeesoft** [lijinma/wechat_spider#19]
`Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/usr/local/lib/node_modules/wechat_spider/node_modules/sqlite3/lib/trace.js:19:31)`

**Comment by jesonray** [comment]
`Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/usr/local/lib/node_modules/wechat_spider/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/usr/local/lib/node_modules/wechat_spider/node_modules/sqlite3/lib/trace.js:19:31)`

**Comment by imwaco** [comment]
遇到同样的问题，一直在刚开始的页面刷新，怀疑是某个js脚本没生效导致没有自动翻页刷新。。。

**Comment by shiliu520** [comment]
我也是，都没自动停止

**Comment by helloyaojun** [comment]
有解决方法吗？

**Comment by wuxianghou** [comment]
没有解决方案吗？

**Comment by MasterVan** [comment]
我也遇到了

**Comment by janily** [comment]
我也遇到了，有解决方案么

**Comment by LunarModule** [comment]
我也是这个情况，大家怎么解决的？

**Comment by koalaauto** [comment]
+1

**Comment by AlwaysBee** [comment]
同样问题，作者会解决么？
