### ISSUE TITLE
求一个正确安装姿势。。

### ISSUE THREAD

**Issue by loongws** [lijinma/wechat_spider#8]
windows 7
node:v6.3.1
npm:4.4.4
python:2.7.13
vs2017 已经可以正常运行c++项目
windows 8.1 sdk也已经安装了
以下是报错信息：
C:\Users\Administrator\AppData\Roaming\npm\wechat_spider -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\wechat_spider\bin\wechat_spider

> iconv@2.2.3 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\iconv
> node-gyp rebuild

C:\Users\Administrator\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [C:\Users\Administrator\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\iconv\buil
d\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\node.js\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\wechat_spider\node_modules\iconv
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
C:\Users\Administrator\AppData\Roaming\npm
`-- (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-04-10T08_33_49_620Z-debug.log

**Comment by lijinma** [comment]
https://github.com/lijinma/wechat_spider/issues/2  看下这个 issue

**Comment by lyixi** [comment]
同样遇到这个问题，请问解决了吗
